apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-guestbook 
  namespace: argocd
spec:
  destination:
    namespace: apps-guestbook
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: manifests/guestbook
    repoURL: https://github.com/devsres-com/gitops-demonstration.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
