apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-cwagent 
  namespace: argocd
spec:
  destination:
    namespace: amazon-cloudwatch
    server: https://kubernetes.default.svc
  project: system-apps 
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: manifests/system-apps/aws/cwagent
    repoURL: https://github.com/devsres-com/gitops-demonstration.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
