apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-haproxy 
  namespace: argocd
spec:
  destination:
    namespace: ingress-haproxy
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: haproxy-ingress 
    repoURL: https://haproxy-ingress.github.io/charts 
    targetRevision: 0.13.6 
    helm:
      values: |
        controller.ingressClassResource: enabled
        controller.ingressClassResource: default	
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
