apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-apps-common
  namespace: argocd
spec:
  destination:
    namespace: system-apps
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: applications/system-apps-common
    repoURL: https://github.com/devsres-com/gitops-demonstration.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  
    syncOptions:
    - CreateNamespace=true
