apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server 
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: system-manifests/metrics-server
    repoURL: https://github.com/devsres-com/gitops-demonstration.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
