apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-podinfo 
  namespace: argocd
spec:
  destination:
    namespace: apps-podinfo
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: manifests/podinfo
    repoURL: git@github.com:devsres-com/gitops-demonstration.git
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
