apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-contour 
  namespace: argocd
spec:
  destination:
    namespace: ingress-contour
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: contour 
    repoURL: https://charts.bitnami.com/bitnami 
    targetRevision: 7.3.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
