apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system-apps
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Aplicativos de sistema para o ArgoCD
  sourceRepos:
  - https://github.com/devsres-com/gitops-demonstration.git
  - https://charts.bitnami.com/bitnami
  - https://grafana.github.io/helm-charts
  - https://haproxy-ingress.github.io/charts
  - https://kubernetes.github.io/ingress-nginx
  - https://prometheus-community.github.io/helm-charts
  destinations:
  - name: '*'
    namespace: '*'
    server: https://kubernetes.default.svc
