apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana 
  namespace: argocd
spec:
  destination:
    namespace: prometheus 
    server: https://kubernetes.default.svc
  project: system-apps
  source:
    chart: grafana 
    repoURL:  https://grafana.github.io/helm-charts
    targetRevision: 6.26.0 
    helm:
      values: |
        ingress.enabled: true
        ingress.hosts: 
          - grafana.eks.devsres.com

  syncPolicy:
    automated:
      prune: true
      selfHeal: true  
    syncOptions:
    - CreateNamespace=true
