apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager 
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: system-apps
  source:
    chart: cert-manager 
    repoURL: https://charts.jetstack.io 
    targetRevision: 1.8.0 
    helm:
      values: |
        installCRDs: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  
    syncOptions:
    - CreateNamespace=true
