apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-podinfo 
  namespace: argocd
spec:
  destination:
    namespace: apps-podinfo
    server: https://kubernetes.default.svc
  project: client-apps-client2 
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: manifests/podinfo
    repoURL: https://github.com/devsres-com/gitops-demonstration.git 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
